// GENERATED by /demo-video assemble.js - DO NOT EDIT.
// Source of truth: video/storyboard.json (+ narration.json). Re-run assemble.
import { fromAnsi } from "./ansi";
import type { DemoVideoContent } from "./demovideo-types";

/** Short cut: drives Vertical (9:16, 1:1 crop) and Wide (16:9 short). */
export const DEMO_VIDEO: DemoVideoContent = {
  fps: 30, width: 1080, height: 1920,
  title: "soundtag",
  totalFrames: 1154,
  scenes: [
  {
    id: "hook", kind: "title",
    startFrame: 0, durationFrames: 188,
    audio: "audio/hook.wav",
    words: [{"w":"A","startFrame":0,"endFrame":22},{"w":"song","startFrame":22,"endFrame":31},{"w":"you","startFrame":31,"endFrame":38},{"w":"send","startFrame":38,"endFrame":43},{"w":"someone","startFrame":43,"endFrame":55},{"w":"is","startFrame":55,"endFrame":65},{"w":"a","startFrame":65,"endFrame":67},{"w":"Lincoln","startFrame":67,"endFrame":75},{"w":"a","startFrame":75,"endFrame":82},{"w":"chat.","startFrame":82,"endFrame":91},{"w":"It","startFrame":100,"endFrame":108},{"w":"is","startFrame":108,"endFrame":112},{"w":"gone","startFrame":112,"endFrame":121},{"w":"by","startFrame":121,"endFrame":127},{"w":"the","startFrame":127,"endFrame":131},{"w":"time","startFrame":131,"endFrame":138},{"w":"they","startFrame":138,"endFrame":143},{"w":"scroll","startFrame":143,"endFrame":151},{"w":"past","startFrame":151,"endFrame":163},{"w":"it.","startFrame":163,"endFrame":170}],
    headline: "soundtag", sub: "a song, as an object",
  },
  {
    id: "paste", kind: "browser",
    startFrame: 188, durationFrames: 169,
    audio: "audio/paste.wav",
    words: [{"w":"Paste","startFrame":0,"endFrame":11},{"w":"a","startFrame":11,"endFrame":17},{"w":"Spotify","startFrame":17,"endFrame":28},{"w":"link","startFrame":28,"endFrame":40},{"w":"and","startFrame":40,"endFrame":49},{"w":"the","startFrame":49,"endFrame":52},{"w":"code","startFrame":52,"endFrame":59},{"w":"becomes","startFrame":59,"endFrame":71},{"w":"a","startFrame":71,"endFrame":76},{"w":"thing","startFrame":76,"endFrame":82},{"w":"you","startFrame":82,"endFrame":86},{"w":"can","startFrame":86,"endFrame":91},{"w":"turn","startFrame":91,"endFrame":100},{"w":"at","startFrame":100,"endFrame":115},{"w":"the","startFrame":115,"endFrame":119},{"w":"size","startFrame":119,"endFrame":127},{"w":"it","startFrame":127,"endFrame":131},{"w":"will","startFrame":131,"endFrame":134},{"w":"print.","startFrame":134,"endFrame":143}],
    footage: "footage/paste.webm",
  },
  {
    id: "change", kind: "browser",
    startFrame: 357, durationFrames: 240,
    audio: "audio/change.wav",
    words: [{"w":"The","startFrame":0,"endFrame":5},{"w":"plate","startFrame":5,"endFrame":14},{"w":"stops","startFrame":14,"endFrame":25},{"w":"at","startFrame":25,"endFrame":33},{"w":"one","startFrame":33,"endFrame":40},{"w":"height","startFrame":40,"endFrame":50},{"w":"and","startFrame":50,"endFrame":61},{"w":"the","startFrame":61,"endFrame":63},{"w":"code","startFrame":63,"endFrame":71},{"w":"starts","startFrame":71,"endFrame":82},{"w":"exactly","startFrame":82,"endFrame":95},{"w":"there.","startFrame":95,"endFrame":109},{"w":"One","startFrame":124,"endFrame":129},{"w":"filament","startFrame":129,"endFrame":139},{"w":"change","startFrame":139,"endFrame":150},{"w":"for","startFrame":150,"endFrame":157},{"w":"the","startFrame":157,"endFrame":159},{"w":"whole","startFrame":159,"endFrame":166},{"w":"print,","startFrame":166,"endFrame":176},{"w":"not","startFrame":187,"endFrame":193},{"w":"one","startFrame":193,"endFrame":201},{"w":"per","startFrame":201,"endFrame":207},{"w":"layer.","startFrame":207,"endFrame":212}],
    footage: "footage/change.webm",
  },
  {
    id: "shapes", kind: "browser",
    startFrame: 597, durationFrames: 213,
    audio: "audio/shapes.wav",
    words: [{"w":"5","startFrame":0,"endFrame":25},{"w":"shapes,","startFrame":25,"endFrame":39},{"w":"add","startFrame":61,"endFrame":62},{"w":"a","startFrame":62,"endFrame":65},{"w":"title","startFrame":65,"endFrame":74},{"w":"and","startFrame":74,"endFrame":82},{"w":"the","startFrame":82,"endFrame":83},{"w":"tag","startFrame":83,"endFrame":91},{"w":"grows","startFrame":91,"endFrame":99},{"w":"to","startFrame":99,"endFrame":104},{"w":"fit","startFrame":104,"endFrame":108},{"w":"it.","startFrame":108,"endFrame":114},{"w":"Because","startFrame":131,"endFrame":136},{"w":"the","startFrame":136,"endFrame":141},{"w":"code","startFrame":141,"endFrame":151},{"w":"is","startFrame":151,"endFrame":156},{"w":"the","startFrame":156,"endFrame":160},{"w":"point","startFrame":160,"endFrame":167},{"w":"of","startFrame":167,"endFrame":171},{"w":"the","startFrame":171,"endFrame":174},{"w":"object.","startFrame":174,"endFrame":183}],
    footage: "footage/shapes.webm",
  },
  {
    id: "cli", kind: "cli",
    startFrame: 810, durationFrames: 137,
    audio: "audio/cli.wav",
    words: [{"w":"The","startFrame":0,"endFrame":8},{"w":"same","startFrame":8,"endFrame":14},{"w":"build","startFrame":14,"endFrame":22},{"w":"on","startFrame":22,"endFrame":28},{"w":"the","startFrame":28,"endFrame":31},{"w":"command","startFrame":31,"endFrame":38},{"w":"line","startFrame":38,"endFrame":49},{"w":"and","startFrame":49,"endFrame":59},{"w":"it","startFrame":59,"endFrame":62},{"w":"tells","startFrame":62,"endFrame":69},{"w":"you","startFrame":69,"endFrame":74},{"w":"which","startFrame":74,"endFrame":82},{"w":"layer","startFrame":82,"endFrame":88},{"w":"to","startFrame":88,"endFrame":94},{"w":"swap","startFrame":94,"endFrame":102},{"w":"on.","startFrame":102,"endFrame":110}],
    cmd: "npx soundtag \"https://open.spotify.com/track/...\"",
    term: fromAnsi("/tmp/demo-out/sweater-weather.3mf\n  /tmp/demo-out/sweater-weather.svg\n75.6 by 21.1 by 3 mm, bar\n  Insert the filament change at layer 13, which starts at z 2.4 mm.\n  material 3.89 cm3, about 4.8 g of PLA\n  contrast 17.6 to 1, which is good\n  the Spotify mark is not extruded. --mark adds it, see TRADEMARKS.md first.\n"),
  },
  {
    id: "close", kind: "still",
    startFrame: 947, durationFrames: 207,
    audio: "audio/close.wav",
    words: [{"w":"MIT,","startFrame":0,"endFrame":18},{"w":"no","startFrame":31,"endFrame":38},{"w":"upload,","startFrame":38,"endFrame":48},{"w":"no","startFrame":60,"endFrame":62},{"w":"account.","startFrame":62,"endFrame":71},{"w":"Everything","startFrame":91,"endFrame":101},{"w":"it","startFrame":101,"endFrame":108},{"w":"claims","startFrame":108,"endFrame":116},{"w":"was","startFrame":116,"endFrame":123},{"w":"measured","startFrame":123,"endFrame":131},{"w":"and","startFrame":131,"endFrame":147},{"w":"what","startFrame":147,"endFrame":152},{"w":"was","startFrame":152,"endFrame":156},{"w":"not","startFrame":156,"endFrame":163},{"w":"is","startFrame":163,"endFrame":169},{"w":"written","startFrame":169,"endFrame":175},{"w":"down.","startFrame":175,"endFrame":185}],
    image: "footage/close.png",
  }
  ],
};

/** Long cut: every scene incl. {"variants":["long"]} ones, drives WideLong. */
export const DEMO_VIDEO_LONG: DemoVideoContent = {
  fps: 30, width: 1080, height: 1920,
  title: "soundtag",
  totalFrames: 1154,
  scenes: [
  {
    id: "hook", kind: "title",
    startFrame: 0, durationFrames: 188,
    audio: "audio/hook.wav",
    words: [{"w":"A","startFrame":0,"endFrame":22},{"w":"song","startFrame":22,"endFrame":31},{"w":"you","startFrame":31,"endFrame":38},{"w":"send","startFrame":38,"endFrame":43},{"w":"someone","startFrame":43,"endFrame":55},{"w":"is","startFrame":55,"endFrame":65},{"w":"a","startFrame":65,"endFrame":67},{"w":"Lincoln","startFrame":67,"endFrame":75},{"w":"a","startFrame":75,"endFrame":82},{"w":"chat.","startFrame":82,"endFrame":91},{"w":"It","startFrame":100,"endFrame":108},{"w":"is","startFrame":108,"endFrame":112},{"w":"gone","startFrame":112,"endFrame":121},{"w":"by","startFrame":121,"endFrame":127},{"w":"the","startFrame":127,"endFrame":131},{"w":"time","startFrame":131,"endFrame":138},{"w":"they","startFrame":138,"endFrame":143},{"w":"scroll","startFrame":143,"endFrame":151},{"w":"past","startFrame":151,"endFrame":163},{"w":"it.","startFrame":163,"endFrame":170}],
    headline: "soundtag", sub: "a song, as an object",
  },
  {
    id: "paste", kind: "browser",
    startFrame: 188, durationFrames: 169,
    audio: "audio/paste.wav",
    words: [{"w":"Paste","startFrame":0,"endFrame":11},{"w":"a","startFrame":11,"endFrame":17},{"w":"Spotify","startFrame":17,"endFrame":28},{"w":"link","startFrame":28,"endFrame":40},{"w":"and","startFrame":40,"endFrame":49},{"w":"the","startFrame":49,"endFrame":52},{"w":"code","startFrame":52,"endFrame":59},{"w":"becomes","startFrame":59,"endFrame":71},{"w":"a","startFrame":71,"endFrame":76},{"w":"thing","startFrame":76,"endFrame":82},{"w":"you","startFrame":82,"endFrame":86},{"w":"can","startFrame":86,"endFrame":91},{"w":"turn","startFrame":91,"endFrame":100},{"w":"at","startFrame":100,"endFrame":115},{"w":"the","startFrame":115,"endFrame":119},{"w":"size","startFrame":119,"endFrame":127},{"w":"it","startFrame":127,"endFrame":131},{"w":"will","startFrame":131,"endFrame":134},{"w":"print.","startFrame":134,"endFrame":143}],
    footage: "footage/paste.webm",
  },
  {
    id: "change", kind: "browser",
    startFrame: 357, durationFrames: 240,
    audio: "audio/change.wav",
    words: [{"w":"The","startFrame":0,"endFrame":5},{"w":"plate","startFrame":5,"endFrame":14},{"w":"stops","startFrame":14,"endFrame":25},{"w":"at","startFrame":25,"endFrame":33},{"w":"one","startFrame":33,"endFrame":40},{"w":"height","startFrame":40,"endFrame":50},{"w":"and","startFrame":50,"endFrame":61},{"w":"the","startFrame":61,"endFrame":63},{"w":"code","startFrame":63,"endFrame":71},{"w":"starts","startFrame":71,"endFrame":82},{"w":"exactly","startFrame":82,"endFrame":95},{"w":"there.","startFrame":95,"endFrame":109},{"w":"One","startFrame":124,"endFrame":129},{"w":"filament","startFrame":129,"endFrame":139},{"w":"change","startFrame":139,"endFrame":150},{"w":"for","startFrame":150,"endFrame":157},{"w":"the","startFrame":157,"endFrame":159},{"w":"whole","startFrame":159,"endFrame":166},{"w":"print,","startFrame":166,"endFrame":176},{"w":"not","startFrame":187,"endFrame":193},{"w":"one","startFrame":193,"endFrame":201},{"w":"per","startFrame":201,"endFrame":207},{"w":"layer.","startFrame":207,"endFrame":212}],
    footage: "footage/change.webm",
  },
  {
    id: "shapes", kind: "browser",
    startFrame: 597, durationFrames: 213,
    audio: "audio/shapes.wav",
    words: [{"w":"5","startFrame":0,"endFrame":25},{"w":"shapes,","startFrame":25,"endFrame":39},{"w":"add","startFrame":61,"endFrame":62},{"w":"a","startFrame":62,"endFrame":65},{"w":"title","startFrame":65,"endFrame":74},{"w":"and","startFrame":74,"endFrame":82},{"w":"the","startFrame":82,"endFrame":83},{"w":"tag","startFrame":83,"endFrame":91},{"w":"grows","startFrame":91,"endFrame":99},{"w":"to","startFrame":99,"endFrame":104},{"w":"fit","startFrame":104,"endFrame":108},{"w":"it.","startFrame":108,"endFrame":114},{"w":"Because","startFrame":131,"endFrame":136},{"w":"the","startFrame":136,"endFrame":141},{"w":"code","startFrame":141,"endFrame":151},{"w":"is","startFrame":151,"endFrame":156},{"w":"the","startFrame":156,"endFrame":160},{"w":"point","startFrame":160,"endFrame":167},{"w":"of","startFrame":167,"endFrame":171},{"w":"the","startFrame":171,"endFrame":174},{"w":"object.","startFrame":174,"endFrame":183}],
    footage: "footage/shapes.webm",
  },
  {
    id: "cli", kind: "cli",
    startFrame: 810, durationFrames: 137,
    audio: "audio/cli.wav",
    words: [{"w":"The","startFrame":0,"endFrame":8},{"w":"same","startFrame":8,"endFrame":14},{"w":"build","startFrame":14,"endFrame":22},{"w":"on","startFrame":22,"endFrame":28},{"w":"the","startFrame":28,"endFrame":31},{"w":"command","startFrame":31,"endFrame":38},{"w":"line","startFrame":38,"endFrame":49},{"w":"and","startFrame":49,"endFrame":59},{"w":"it","startFrame":59,"endFrame":62},{"w":"tells","startFrame":62,"endFrame":69},{"w":"you","startFrame":69,"endFrame":74},{"w":"which","startFrame":74,"endFrame":82},{"w":"layer","startFrame":82,"endFrame":88},{"w":"to","startFrame":88,"endFrame":94},{"w":"swap","startFrame":94,"endFrame":102},{"w":"on.","startFrame":102,"endFrame":110}],
    cmd: "npx soundtag \"https://open.spotify.com/track/...\"",
    term: fromAnsi("/tmp/demo-out/sweater-weather.3mf\n  /tmp/demo-out/sweater-weather.svg\n75.6 by 21.1 by 3 mm, bar\n  Insert the filament change at layer 13, which starts at z 2.4 mm.\n  material 3.89 cm3, about 4.8 g of PLA\n  contrast 17.6 to 1, which is good\n  the Spotify mark is not extruded. --mark adds it, see TRADEMARKS.md first.\n"),
  },
  {
    id: "close", kind: "still",
    startFrame: 947, durationFrames: 207,
    audio: "audio/close.wav",
    words: [{"w":"MIT,","startFrame":0,"endFrame":18},{"w":"no","startFrame":31,"endFrame":38},{"w":"upload,","startFrame":38,"endFrame":48},{"w":"no","startFrame":60,"endFrame":62},{"w":"account.","startFrame":62,"endFrame":71},{"w":"Everything","startFrame":91,"endFrame":101},{"w":"it","startFrame":101,"endFrame":108},{"w":"claims","startFrame":108,"endFrame":116},{"w":"was","startFrame":116,"endFrame":123},{"w":"measured","startFrame":123,"endFrame":131},{"w":"and","startFrame":131,"endFrame":147},{"w":"what","startFrame":147,"endFrame":152},{"w":"was","startFrame":152,"endFrame":156},{"w":"not","startFrame":156,"endFrame":163},{"w":"is","startFrame":163,"endFrame":169},{"w":"written","startFrame":169,"endFrame":175},{"w":"down.","startFrame":175,"endFrame":185}],
    image: "footage/close.png",
  }
  ],
};
